# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frk < Formula
  desc "frk is summary generator for your GitHub activities."
  homepage "https://github.com/winebarrel/frk"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/frk/releases/download/v1.0.0/frk_1.0.0_darwin_arm64.tar.gz"
      sha256 "666a187381bf9754ba5fcce676b307620e7787ce7580b3db691f03911ed44645"

      def install
        bin.install 'frk'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/frk/releases/download/v1.0.0/frk_1.0.0_darwin_amd64.tar.gz"
      sha256 "7a8571b8879c52a57d6a4c111fde294edfa36f0032e8442d7b220d486e4bdc42"

      def install
        bin.install 'frk'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/frk/releases/download/v1.0.0/frk_1.0.0_linux_arm64.tar.gz"
      sha256 "aa4e016d107b7939723e3d77c9d2523d686c67168496056561275778129f41a6"

      def install
        bin.install 'frk'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/frk/releases/download/v1.0.0/frk_1.0.0_linux_amd64.tar.gz"
      sha256 "912118096f042cddcefdc5b57dd984cd5635870a4190495a2400e62bc3cd0302"

      def install
        bin.install 'frk'
      end
    end
  end
end
