# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frk < Formula
  desc "frk is summary generator for your GitHub activities."
  homepage "https://github.com/winebarrel/frk"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/frk/releases/download/v1.1.0/frk_1.1.0_darwin_amd64.tar.gz"
      sha256 "44ff0146155ecbd66c997e835c8f3ed22b0e3272f4822cc3a886df621d2bec55"

      def install
        bin.install 'frk'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/frk/releases/download/v1.1.0/frk_1.1.0_darwin_arm64.tar.gz"
      sha256 "26da119b1c8a4ef0789018165c0788483c02fcc811df3f55a397e5c551275e4c"

      def install
        bin.install 'frk'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/frk/releases/download/v1.1.0/frk_1.1.0_linux_arm64.tar.gz"
      sha256 "fa32dc2f02449e499e9c768fa70ba7ebad2fffde5cb07b6c3301c6a930dbeca3"

      def install
        bin.install 'frk'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/frk/releases/download/v1.1.0/frk_1.1.0_linux_amd64.tar.gz"
      sha256 "6b1a384b81834adecfcd65ea78102c823c8410b581c6a7da3e90c862e8734bb7"

      def install
        bin.install 'frk'
      end
    end
  end
end
